### ISSUE TITLE
不能识别芯片

### ISSUE THREAD

**Issue by Thawnoy** [FASTSHIFT/WatchX#12]
你好Utility和MDK都无法连接到设备

**Comment by FASTSHIFT** [comment]
检查MCU供电脚电压是否正常。
检查SWD接口是否有短路或断路。
焊接QFN芯片需要把底下焊锡挤出来，不然很容易短路。

**Comment by Thawnoy** [comment]
谢谢指点，但是发现晶振输出的频率不对，是不是因为这个
