### ISSUE TITLE
lvgl只能显示一半的图片

### ISSUE THREAD

**Issue by Thawnoy** [FASTSHIFT/WatchX#13]
移植了楼主的lvgl显示驱动，在1.14寸屏幕上只能显示一般的图案

**Comment by FASTSHIFT** [comment]
DMA单次传输的数据量有限，如果单次传输数据量大于65535，需要拆包处理，参考 https://github.com/FASTSHIFT/X-TRACK/blob/main/Software/X-Track/MDK-ARM_F403A/Platform/HAL/HAL_Display.cpp

**Comment by Thawnoy** [comment]
首先感谢指教。但是十分抱歉，文本打错字了，我的issue是屏幕上只显示一半图片。十分感谢



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年07月03日 21:37 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [FASTSHIFT/WatchX] lvgl只能显示一半的图片 (Issue #13) |

DMA单次传输的数据量有限，如果单次传输数据量大于65535，需要拆包处理，参考 https://github.com/FASTSHIFT/X-TRACK/blob/main/Software/X-Track/MDK-ARM_F403A/Platform/HAL/HAL_Display.cpp

**Comment by FASTSHIFT** [comment]
发图和代码

**Comment by Thawnoy** [comment]
图片和代码发到了github提供的邮箱中，如果方便请提供一下联系方式，有许多这个项目问题希望得到解答
















在 2022-07-03 22:18:12，"_VIFEXTech" ***@***.***> 写道：

发图和代码

**Comment by FASTSHIFT** [comment]
> 图片和代码发到了github提供的邮箱中，如果方便请提供一下联系方式，有许多这个项目问题希望得到解答 在 2022-07-03 22:18:12，"_VIFEXTech" ***@***.***> 写道： 发图和代码 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

issue也能贴图片。
先确保屏幕驱动没有问题再上LVGL，这个现象看着像分辨率设置或者屏幕方向设置的问题。

**Comment by Thawnoy** [comment]
![图片](https://user-images.githubusercontent.com/108125454/177294324-15c286c0-1e05-4042-b4db-2e8854ab5c5b.png)
你好，我注册这两个事件之后，显示更新也变成200ms运行一次，您知道原因吗

**Comment by FASTSHIFT** [comment]
@Thawnoy 
注册的任务必须是非阻塞的

**Comment by Thawnoy** [comment]
![IMG_20220706_202416](https://user-images.githubusercontent.com/108125454/177549470-21b9b83c-2d7e-45a8-bc98-7ce180f880e6.jpg)
您好，您知道这个现象是为什么吗

**Comment by FASTSHIFT** [comment]
> ![IMG_20220706_202416](https://user-images.githubusercontent.com/108125454/177549470-21b9b83c-2d7e-45a8-bc98-7ce180f880e6.jpg) 您好，您知道这个现象是为什么吗

lv_demo_widgets/benchmark可以正常跑吗？先排除驱动问题。再检查应用层是不是哪里内存越界导致的运行异常，建议UI开发工作转移到PC模拟器上进行开发，有[ASAN](https://docs.microsoft.com/zh-cn/cpp/sanitizers/asan?view=msvc-170)进行辅助很容易发现问题。

**Comment by FASTSHIFT** [comment]
> ![IMG_20220706_202416](https://user-images.githubusercontent.com/108125454/177549470-21b9b83c-2d7e-45a8-bc98-7ce180f880e6.jpg) 您好，您知道这个现象是为什么吗

lv_demo_widgets/benchmark可以正常跑吗？先排除驱动问题。再检查应用层是不是哪里内存越界导致的运行异常，建议UI开发工作转移到PC模拟器上进行开发，有[ASAN](https://docs.microsoft.com/zh-cn/cpp/sanitizers/asan?view=msvc-170)进行辅助很容易发现问题。

**Comment by Thawnoy** [comment]
你好，感谢回复，但是lvgl6.1.1的benchmark例程是要触屏的，其他的tutorial例程运行正常

**Comment by Thawnoy** [comment]
你好，benchmark的例程需要触摸驱动，但是试了一下animation的例程有的时候颜色会乱掉了。另外运行这套UI的时候会死机
