### ISSUE TITLE
Info Please

### ISSUE THREAD

**Issue by DeonMarais64** [FASTSHIFT/WatchX#2]
Hi,
This is a really cool project/product ! IMO it has a lot of scope and possibilities !

I am an embedded developer and amateur endurance athlete ( https://www.strava.com/athletes/12265248 ) and the prospect of being able to tinker with the wrist unit I use is very appealing to me even though it may not be sufficiently rugged for general use but for my purposes this is not a big problem.

Some questions,
1. Can I buy one or two units, If so where from and how ?
2. Do you have any plans to add Bluetooth and maybe WiFi to the hardware at some point ?
3. I have been using LVGL for a few years now and generally use the IAR compiler.
I am be willing to adapt the project to IAR for both IAR and Eclipse IDE's and in future VisualGDB ( https://visualgdb.com/ ) using either IAR and/Or GNU Compilers. I am also willing to migrate the source code for LVGL V7.x compatibility. Would you welcome collaboration in this regard ?

Looking forward to your response.

**Comment by FASTSHIFT** [comment]
@DeonMarais64 
1. International express delivery may be inconvenient, you can refer to the PCB in the "Hardware" folder for production.
2. I will consider adding Bluetooth and WiFi. ESP32 is a good choice.
3. It should be easy to port this program to IAR for compilation. I will try it later.
