### ISSUE TITLE
您好，想请问一下外部的两个晶振的频率是8MHz和32.768KHz吗

### ISSUE THREAD

**Issue by vegetableno1** [FASTSHIFT/WatchX#8]
这是一个很棒的项目，我想复现一个学习一下，但是发现元器件清单中的2016晶振没有标明频率，想要请教一下。非常期待您的回复！

**Comment by FASTSHIFT** [comment]
![image](https://user-images.githubusercontent.com/26767803/133183722-56df1c1d-3ab3-4bc3-b892-85f12d732bf1.png)

**Comment by vegetableno1** [comment]
啊好的，非常感谢！
