### ISSUE TITLE
请问为什么选择使用开关电源而不是线性电源呢

### ISSUE THREAD

**Issue by 952736147** [FASTSHIFT/WatchX#9]
我最近也在做一款类似的手表，看到您的项目很有帮助。我认为在这种情况下使用线性电源有以下优点：
1.外围元件少，节省布线空间
2.单节锂电池降压到3.3V，也有80~90%的效率
请问您为什么选择使用开关电源呢？是为了追求尽可能高的电源效率还是有其他考虑呢

**Comment by FASTSHIFT** [comment]
可以换线性电源，后面的X-TRACK项目用的就是线性稳压。

**Comment by 952736147** [comment]
谢谢😊
